# vim:ft=ansible:

---
- hosts: "{{ hosts }}"
  tasks:
    - name: Install my own debian repo
      apt_repository:
        repo: deb [trusted=yes] https://debian-stretch-repo.s3.amazonaws.com stable main
        state: present
      become: yes

    - name: Install packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - ack
          - build-essential
          - git
          - htop
          - python3.7
          - python-pip
          - rubygems
          - ruby-dev
          - tmux
          - tree
          - zsh
      become: yes

    - name: Create temp directory
      tempfile:
        state: directory
        suffix: temp
      register: temp_dir

    - name: Download neovim
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v0.3.8/nvim-linux64.tar.gz"
        dest: "{{ temp_dir.path }}"

    - name: Install neovim
      command: "tar xzf {{ temp_dir.path }}/nvim-linux64.tar.gz -C /usr/local --strip-components 1"
      become: yes

    - name: Install neovim python2 module
      command: pip install neovim
      become: yes

    - name: Install neovim python3 module
      command: pip3.7 install neovim
      become: yes

    - name: Install neovim ruby gem
      command: gem install neovim
      become: yes

    - name: Add zsh as shell
      command: add-shell /usr/bin/zsh
      become: yes

    - name: Make admin's shell zsh
      command: chsh --shell /usr/bin/zsh admin
      become: yes

    - name: Download dotfiles
      git:
        repo: "https://github.com/jacklund/dotfiles.git"
        dest: git/dotfiles

    - name: Install dotfiles
      shell: ./install.sh
      args:
        chdir: git/dotfiles

    - name: Download FZF
      git:
        repo: "https://github.com/junegunn/fzf.git"
        depth: 1
        dest: .fzf

    - name: Install FZF
      shell: .fzf/install --all

    - name: Install rust
      shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

    - name: Download nodejs
      get_url:
        url: "https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz"
        dest: "{{ temp_dir.path }}"

    - name: Install nodejs
      command: "tar xJf {{ temp_dir.path }}/node-v10.16.3-linux-x64.tar.xz -C /usr/local/ --strip-components 1"
      become: yes

    - name: Install neovim npm package
      command: npm install -g neovim
      become: yes

      name: Install nvim plugins
      command: nvim +'Pluginstall --sync' +qa
